[package]
name = "dg"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
hotwatch = "0.5.0"
log = "0.4.22"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
tokio = { version = "1.40.0", features = ["full"] }
